### PR TITLE
Newsweek Clone Bootstrap Project

### PR DESCRIPTION
**Pull request by frankopkusianwar**
#### What does this PR do?

- Shows how to work with bootstrap

### Description of Task to be completed?

 - Add the HTML index file
 - Add Bootstrap and CSS to design the page 
 - Run validations on Html and CSS. 

#### How should this be manually tested? 

- Clone this branch. 
- open the index.html file on your browser 

#### Screenshot 

screenshot

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @frankopkusianwar, great job with this project 👍 Pull Request is very professional, it has a title and a beautiful description 🙂 Commit messages are descriptive 👐 README looks professional. Before we can proceed, let us address the following comments:
* Let us reduce the size of our CSS file by applying the DRY rule. An example image below
boot
There are many others, we can refactor. Let us look into it
* Let us use more of the bootstrap classes since using the classes is the main idea of this project
* Let us update the README file with the appropriate live link and add our email to the author section
* Let us fix the responsiveness of the project for medium and small devices. I have a few screenshots I took to give you a clear picture of what we currently have. You can change the screen sizes so you have a feel of it
med2
med1
mednav
med
smm1
smm
 
Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by men32z — COMMENTED** [review]
## Pull request currently under review by Luis Preza (TSE).

Kindly exercise patience 🐱

**Review by men32z — COMMENTED** [review]
Hey @frankopkusianwar !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍


### Required changes
Remember that this is a clone page so it should be as closest as possible to the original, here are some requirements.

- [x] Header should have the original logo

- [x] Fix the red div that is in search bar in wide version
Screenshot_2020-04-02 NewsWeek Clone

- [x] Header in mobile and mid version should be full width
#### your version

bbbbbb

#### original version
áaaaa

- [x] Header in mobile version is loosing styles 

cccccc

- [x] Add tags to images that should have
Screenshot_2020-04-02 Newsweek(1)

- [x] this part almost in footer changes with the sizes, kindly fix them 

#### your version
Screenshot_2020-04-02 NewsWeek Clone(1)
#### original version
Screenshot_2020-04-02 Newsweek

- [x] check the images in all the sizes and fix those which are distorted

Screenshot_2020-04-02 NewsWeek Clone

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @frankopkusianwar  :wave:
-
You have done a splendid job! :tada:  Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## [OPTIONAL] - Friendly reminder: 
Always aim to adhere to the strictest rules when using the  Github/Git Flow in all your projects. The same was not quite applied to this project.
 ## [REQUIRED] - FIX - The general styling of the page.
Having reviewed your code, I noticed your use of some of the essential bootstrap classes that would make the page come out lively was not used properly. 
- A case could be made with the use of the `container-fluid` class, it makes our page span the entire screen width. 
- As a result, we get this in return:
newsweek_clone
 - Kindly fix this with the appropriate class. I'd suggest we match what Newsweek's done with their site instead:
newsweek

- Use the `container` class in place of all the `container-fluid` class to achieve this; Read more [here](https://stackoverflow.com/questions/22262311/container-fluid-vs-container) on what makes them different.
## [REQUIRED] FIX - The in the magazine section.
There is some whitespace in the 'in the magazine section'. fix that.
in_the_magazine
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by bolah2009 — APPROVED** [review]
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

The navbar is stilled messed up, kindly fix this before merging.
Check the illustration before for steps to reproduce these issues.
SUGGESTION: You can add a media query to reduce the font size for smaller screens so that the menu items can contain its container without unnecessary wrapping.

| [Current Clone](https://rawcdn.githack.com/frankopkusianwar/NewsweekClone/c142c0d78fe5e8284c54d3cece9d290e2d072070/index.html) | [Newsweek Page](https://www.newsweek.com/) |
| :----: | :----: |
| newsweek clone | newsweek current  |



Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Pull request merged**
